#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options, TaskGen
import waflib.Logs as Logs, waflib.Utils as Utils
import os
import sys
import platform as PLATFORM
import re
import subprocess
import glob

@TaskGen.extension('.m')
def m_hook(self, node):
    """Alias .m files to be compiled the same as .c files, gcc will do the right thing."""
    return self.create_compiled_task('c', node)

gtk2_ardour_sources = [
        'app-core/about.cc',
        'app-core/actions.cc',
        'session-config-dialogs/add_route_dialog.cc',
        'import-export-video/ambiguous_file_dialog.cc',
        'import-export-video/analysis_window.cc',
        'app-core/application_bar.cc',
        'session-config-dialogs/ardour_color_dialog.cc',
        'app-core/ardour_dialog.cc',
        'platform-support/ardour_http.cc',
        'app-core/ardour_message.cc',
        'app-core/ardour_ui.cc',
        'app-core/ardour_ui2.cc',
        'app-core/ardour_ui3.cc',
        'app-core/ardour_ui_aaf.cc',
        'app-core/ardour_ui_access_web.cc',
        'app-core/ardour_ui_dependents.cc',
        'app-core/ardour_ui_dialogs.cc',
        'app-core/ardour_ui_ed.cc',
        'app-core/ardour_ui_engine.cc',
        'app-core/ardour_ui_keys.cc',
        'app-core/ardour_ui_mixer.cc',
        'app-core/ardour_ui_options.cc',
        'app-core/ardour_ui_session.cc',
        'app-core/ardour_ui_startup.cc',
        'app-core/ardour_ui_video.cc',
        'app-core/ardour_window.cc',
        'transport-clocks/audio_clock.cc',
        'editor-view/audio_clip_editor.cc',
        'editor-view/audio_region_editor.cc',
        'editor-view/audio_region_view.cc',
        'editor-view/audio_trigger_properties_box.cc',
        'editor-view/audio_streamview.cc',
        'editor-view/audio_time_axis.cc',
        'automation/automation_controller.cc',
        'automation/automation_line.cc',
        'editor-view/automation_region_view.cc',
        'editor-view/automation_streamview.cc',
        'automation/automation_text_entry.cc',
        'automation/automation_time_axis.cc',
        'editor-view/axis_view.cc',
        # 'shared-ui/beatbox_gui.cc',
        'session-config-dialogs/bbt_marker_dialog.cc',
        'transport-clocks/big_clock_window.cc',
        'transport-clocks/big_transport_window.cc',
        'editor-view/boundary.cc',
        'app-core/bundle_manager.cc',
        'app-core/canvas_icon.cc',
        'midi-pianoroll/chord_box.cc',
        'midi-pianoroll/chord_dialog.cc',
        'midi-pianoroll/chord_editor.cc',
        'transport-clocks/clock_group.cc',
        'session-config-dialogs/color_theme_manager.cc',
        'session-config-dialogs/configinfo.cc',
        'editor-view/control_point.cc',
        'editor-view/control_point_dialog.cc',
        'mixer/routing/control_slave_ui.cc',
        'editor-view/cross_cursor.cc',
        'clips-cues-trigger/cuebox_ui.cc',
        'clips-cues-trigger/cue_editor.cc',
        'shared-ui/curvetest.cc',
        'platform-support/debug.cc',
        'mixer/meters-monitoring/dsp_stats_ui.cc',
        'mixer/meters-monitoring/dsp_stats_window.cc',
        'session-config-dialogs/duplicate_routes_dialog.cc',
        'midi-pianoroll/edit_note_dialog.cc',
        'editor-view/editing.cc',
        'editor-view/editing_context.cc',
        'editor-view/editor.cc',
        'editor-view/editor_actions.cc',
        'editor-view/editor_automation_line.cc',
        'editor-view/editor_audio_import.cc',
        'editor-view/editor_pt_import.cc',
        'editor-view/editor_audiotrack.cc',
        'editor-view/editor_canvas.cc',
        'editor-view/editor_canvas_events.cc',
        'editor-view/editor_component.cc',
        'editor-view/editor_cursors.cc',
        'editor-view/editor_drag.cc',
        'editor-view/editor_route_groups.cc',
        'editor-view/editor_section_box.cc',
        'editor-view/editor_export_audio.cc',
        'editor-view/editor_group_tabs.cc',
        'editor-view/editor_keys.cc',
        'editor-view/editor_locations.cc',
        'editor-view/editor_markers.cc',
        'editor-view/editor_mixer.cc',
        'editor-view/editor_mouse.cc',
        'editor-view/editor_ops.cc',
        'editor-view/editor_regions.cc',
        'editor-view/editor_routes.cc',
        'editor-view/editor_rulers.cc',
        'editor-view/editor_sections.cc',
        'editor-view/editor_selection.cc',
        'editor-view/editor_snapshots.cc',
        'editor-view/editor_sources.cc',
        'editor-view/editor_summary.cc',
        'editor-view/editor_tempodisplay.cc',
        'editor-view/editor_timefx.cc',
        'editor-view/editor_vsummary.cc',
        'session-config-dialogs/engine_dialog.cc',
        'app-core/enums.cc',
        'import-export-video/export_analysis_graphs.cc',
        'import-export-video/export_channel_selector.cc',
        'import-export-video/export_dialog.cc',
        'import-export-video/export_file_notebook.cc',
        'import-export-video/export_filename_selector.cc',
        'import-export-video/export_format_dialog.cc',
        'import-export-video/export_format_selector.cc',
        'import-export-video/export_preset_selector.cc',
        'import-export-video/export_report.cc',
        'import-export-video/export_timespan_selector.cc',
        'app-core/fitted_canvas_widget.cc',
        'import-export-video/fft.cc',
        'import-export-video/fft_graph.cc',
        'import-export-video/fft_result.cc',
        'app-core/floating_text_entry.cc',
        'mixer/foldback_strip.cc',
        'import-export-video/sfdb_freesound_mootcher.cc',
        'mixer/meters-monitoring/gain_meter.cc',
        'plugins/generic_pluginui.cc',
        'editor-view/ghost_event.cc',
        'editor-view/ghostregion.cc',
        'mixer/routing/global_port_matrix.cc',
        'editor-view/group_tabs.cc',
        'app-core/gui_object.cc',
        'platform-support/idleometer.cc',
        'mixer/meters-monitoring/input_port_monitor.cc',
        'session-config-dialogs/insert_remove_time_dialog.cc',
        'midi-pianoroll/instrument_selector.cc',
        'app-core/interthread_progress_window.cc',
        'mixer/routing/io_button.cc',
        'mixer/routing/io_plugin_window.cc',
        'mixer/routing/io_selector.cc',
        'editor-view/hit.cc',
        'app-core/keyboard.cc',
        'app-core/keyeditor.cc',
        'app-core/led.cc',
        'mixer/meters-monitoring/level_meter.cc',
        'session-config-dialogs/library_download_dialog.cc',
        'shared-ui/location_ui.cc',
        'mixer/meters-monitoring/loudness_dialog.cc',
        'mixer/meters-monitoring/loudness_settings.cc',
        'lua-scripting/lua_script_manager.cc',
        'lua-scripting/luadialog.cc',
        'lua-scripting/luainstance.cc',
        'lua-scripting/luawindow.cc',
        'app-core/main.cc',
        'transport-clocks/main_clock.cc',
        'editor-view/marker.cc',
        'editor-view/mergeable_line.cc',
        'automation/midi_automation_line.cc',
        'midi-pianoroll/midi_channel_dialog.cc',
        'midi-pianoroll/midi_channel_selector.cc',
        'midi-pianoroll/midi_cut_buffer.cc',
        'midi-pianoroll/midi_export_dialog.cc',
        'midi-pianoroll/midi_inspector.cc',
        'midi-pianoroll/midi_list_editor.cc',
        'midi-pianoroll/midi_region_view.cc',
        'midi-pianoroll/midi_trigger_properties_box.cc',
        'midi-pianoroll/midi_selection.cc',
        'editor-view/midi_streamview.cc',
        'midi-pianoroll/midi_time_axis.cc',
        'midi-pianoroll/midi_tracer.cc',
        'midi-pianoroll/midi_util.cc',
        'midi-pianoroll/midi_velocity_dialog.cc',
        'midi-pianoroll/midi_view.cc',
        'midi-pianoroll/midi_view_background.cc',
        'editor-view/mini_timeline.cc',
        'session-config-dialogs/missing_file_dialog.cc',
        'session-config-dialogs/missing_filesource_dialog.cc',
        'plugins/missing_plugin_dialog.cc',
        'mixer/mixer_group_tabs.cc',
        'mixer/mixer_strip.cc',
        'mixer/mixer_ui.cc',
        'mixer/meters-monitoring/meterbridge.cc',
        'mixer/meters-monitoring/meter_strip.cc',
        'mixer/meters-monitoring/meter_patterns.cc',
        'mixer/meters-monitoring/monitor_section.cc',
        'mixer/pan-knob/mono_panner.cc',
        'mixer/pan-knob/mono_panner_editor.cc',
        'app-core/mouse_cursors.cc',
        'app-core/nag.cc',
        'plugins/new_plugin_preset_dialog.cc',
        'session-config-dialogs/new_user_wizard.cc',
        'import-export-video/normalize_dialog.cc',
        'midi-pianoroll/note.cc',
        'midi-pianoroll/note_base.cc',
        'midi-pianoroll/note_player.cc',
        'midi-pianoroll/note_select_dialog.cc',
        'session-config-dialogs/nsm.cc',
        'session-config-dialogs/nsmclient.cc',
        'session-config-dialogs/option_editor.cc',
        'session-config-dialogs/opts.cc',
        'mixer/pan-knob/panner2d.cc',
        'mixer/pan-knob/panner_editor.cc',
        'mixer/pan-knob/panner_interface.cc',
        'mixer/pan-knob/panner_ui.cc',
        'midi-pianoroll/patch_change.cc',
        'midi-pianoroll/patch_change_widget.cc',
        'midi-pianoroll/pianokeyboard.cc',
        'midi-pianoroll/piano_key_bindings.cc',
        'midi-pianoroll/piano_roll_header.cc',
        'midi-pianoroll/pianoroll.cc',
        'midi-pianoroll/pianoroll_automation_line.cc',
        'midi-pianoroll/pianoroll_background.cc',
        'midi-pianoroll/pianoroll_velocity.cc',
        'midi-pianoroll/pianoroll_midi_view.cc',
        'midi-pianoroll/pianoroll_window.cc',
        'platform-support/pingback.cc',
        'session-config-dialogs/pitch_color_dialog.cc',
        'editor-view/playlist_lane_time_axis.cc',
        'editor-view/playlist_selector.cc',
        'plugins/plugin_display.cc',
        'plugins/plugin_eq_gui.cc',
        'plugins/plugin_manager_ui.cc',
        'plugins/plugin_pin_dialog.cc',
        'plugins/plugin_presets_ui.cc',
        'plugins/plugin_scan_dialog.cc',
        'plugins/plugin_setup_dialog.cc',
        'plugins/plugin_selector.cc',
        'plugins/plugin_ui.cc',
        'plugins/plugin_dspload_ui.cc',
        'plugins/plugin_dspload_window.cc',
        'plugins/plugin_window_proxy.cc',
        'mixer/routing/port_group.cc',
        'mixer/routing/port_insert_ui.cc',
        'mixer/routing/port_matrix.cc',
        'mixer/routing/port_matrix_body.cc',
        'mixer/routing/port_matrix_column_labels.cc',
        'mixer/routing/port_matrix_component.cc',
        'mixer/routing/port_matrix_grid.cc',
        'mixer/routing/port_matrix_labels.cc',
        'mixer/routing/port_matrix_row_labels.cc',
	'shared-ui/prh.cc',
	'shared-ui/prh_base.cc',
	'plugins/processor_box.cc',
        'mixer/routing/processor_selection.cc',
        'midi-pianoroll/patch_change_dialog.cc',
        'app-core/progress_reporter.cc',
        'import-export-video/pt_import_selector.cc',
        'editor-view/public_editor.cc',
        'session-config-dialogs/quantize_dialog.cc',
        'session-config-dialogs/rc_option_editor.cc',
        'session-config-dialogs/rec_info_box.cc',
        'session-config-dialogs/recorder_group_tabs.cc',
        'session-config-dialogs/recorder_ui.cc',
        'editor-view/region_editor.cc',
        'editor-view/region_editor_window.cc',
        'editor-view/region_fx_line.cc',
        'editor-view/region_fx_properties_box.cc',
        'editor-view/region_gain_line.cc',
        'editor-view/region_layering_order_editor.cc',
        'editor-view/region_list_base.cc',
        'editor-view/region_peak_cursor.cc',
        'editor-view/region_selection.cc',
        'editor-view/region_ui_settings.cc',
        'editor-view/region_view.cc',
        'mixer/routing/return_ui.cc',
        'shared-ui/rhythm_ferret.cc',
        'session-config-dialogs/route_comment_editor.cc',
        'editor-view/route_group_dialog.cc',
        'editor-view/route_group_menu.cc',
        'editor-view/route_list_base.cc',
        'mixer/routing/route_params_ui.cc',
        'mixer/routing/route_properties_box.cc',
        'mixer/routing/route_processor_selection.cc',
        'editor-view/route_time_axis.cc',
        'editor-view/route_ui.cc',
        'session-config-dialogs/rta_manager.cc',
        'session-config-dialogs/rta_window.cc',
        'editor-view/ruler_dialog.cc',
        'session-config-dialogs/save_as_dialog.cc',
        'session-config-dialogs/save_template_dialog.cc',
        'session-config-dialogs/search_path_option.cc',
        'platform-support/screensaver.cc',
        'session-config-dialogs/script_selector.cc',
        'editor-view/selection.cc',
        'editor-view/selection_properties_box.cc',
        'editor-view/selection_memento.cc',
        'mixer/routing/send_ui.cc',
        'session-config-dialogs/session_archive_dialog.cc',
        'session-config-dialogs/session_dialog.cc',
        'session-config-dialogs/session_metadata_dialog.cc',
        'session-config-dialogs/session_option_editor.cc',
        'session-config-dialogs/scale_dialog.cc',
        'import-export-video/sfdb_ui.cc',
        'transport-clocks/shuttle_control.cc',
        'import-export-video/simple_export_dialog.cc',
        'editor-view/slot_properties_box.cc',
        'editor-view/source_list_base.cc',
        'import-export-video/soundcloud_export_selector.cc',
        'app-core/splash.cc',
        'mixer/routing/speaker_dialog.cc',
        'session-config-dialogs/startup_fsm.cc',
        'midi-pianoroll/step_editor.cc',
        'midi-pianoroll/step_entry.cc',
        'mixer/pan-knob/stereo_panner.cc',
        'mixer/pan-knob/stereo_panner_editor.cc',
        'editor-view/streamview.cc',
        'import-export-video/strip_export_dialog.cc',
        'import-export-video/strip_import_dialog.cc',
        'shared-ui/strip_silence_dialog.cc',
        'editor-view/stripable_colorpicker.cc',
        'editor-view/stripable_time_axis.cc',
        'mixer/surround_strip.cc',
        'midi-pianoroll/sys_ex.cc',
        'session-config-dialogs/template_dialog.cc',
        'editor-view/tempo_curve.cc',
        'editor-view/tempo_dialog.cc',
        'editor-view/grid_lines.cc',
        'editor-view/tempo_map_change.cc',
        'editor-view/time_axis_view.cc',
        'editor-view/time_axis_view_item.cc',
        'shared-ui/time_fx_dialog.cc',
        'transport-clocks/time_info_box.cc',
        'transport-clocks/time_selection.cc',
        'transport-clocks/timectl_gui.cc',
        'app-core/timers.cc',
        'editor-view/track_record_axis.cc',
        'editor-view/track_selection.cc',
        'editor-view/track_view_list.cc',
        'session-config-dialogs/transform_dialog.cc',
        'transport-clocks/transport_control.cc',
        'transport-clocks/transport_control_ui.cc',
        'transport-clocks/transport_masters_dialog.cc',
        'session-config-dialogs/transpose_dialog.cc',
        'clips-cues-trigger/trigger_clip_picker.cc',
        'clips-cues-trigger/trigger_jump_dialog.cc',
        'clips-cues-trigger/trigger_page.cc',
        'clips-cues-trigger/trigger_region_list.cc',
        'clips-cues-trigger/trigger_route_list.cc',
        'clips-cues-trigger/trigger_source_list.cc',
        'clips-cues-trigger/trigger_strip.cc',
        'clips-cues-trigger/trigger_master.cc',
        'clips-cues-trigger/trigger_ui.cc',
        'clips-cues-trigger/triggerbox_ui.cc',
        'session-config-dialogs/ui_config.cc',
        'app-core/utils.cc',
        'transport-clocks/varispeed_dialog.cc',
        'mixer/vca_master_strip.cc',
        'editor-view/verbose_cursor.cc',
        'midi-pianoroll/virtual_keyboard_window.cc',
        'app-core/visibility_group.cc',
        'app-core/window_manager.cc',
        # video-timeline related sources:
        'import-export-video/video_image_frame.cc',
        'import-export-video/add_video_dialog.cc',
        'editor-view/editor_videotimeline.cc',
        'editor-view/vca_time_axis.cc',
        'import-export-video/video_timeline.cc',
        'import-export-video/video_monitor.cc',
	'editor-view/view_background.cc',
        'import-export-video/transcode_ffmpeg.cc',
        'import-export-video/transcode_video_dialog.cc',
        'midi-pianoroll/velocity_display.cc',
        'midi-pianoroll/velocity_ghost_region.cc',
        'import-export-video/video_server_dialog.cc',
        'import-export-video/utils_videotl.cc',
        'import-export-video/export_video_dialog.cc'
]

def enoify (major, minor):
    # Code names based on
    # https://en.wikipedia.org/wiki/Brian_Eno_discography
    #
    # sort Studio albums + Collaborative albums + Compilation albums by Month/Year.
    # (no Singles, no EPs, no Video Albums, no Production)
    if major == 3:
        return "\\n\\\"E-No\\\""
    elif major == 4:
        if minor == 0:
            return "\\n\\\"No Pussyfooting\\\""
        elif minor == 1:
            return "\\n\\\"Here Come the Warm Jets\\\""
        elif minor == 2:
            return "\\n\\\"Taking Tiger Mountain\\\""
        elif minor == 3:
            return "\\n\\\"Lady June's Linguistic Leprosy\\\""
        elif minor == 4:
            return "\\n\\\"Discreet Music\\\""
        elif minor == 5:
            return "\\n\\\"Another Green World\\\""
        elif minor == 6:
            return "\\n\\\"Evening Star\\\""
        elif minor == 7:
            return "\\n\\\"Cluster and Eno\\\""
    elif major == 5:
        if minor == 0:
            return "\\n\\\"Before and After Science\\\""
        elif minor == 1:
            return "\\n\\\"After the Heat\\\""
        elif minor == 2:
            return "\\n\\\"Music for Airports\\\""
        elif minor == 3:
            return "\\n\\\"Music for Films\\\""
        elif minor == 4:
            return "\\n\\\"In a Land of Clear Colours\\\""
        elif minor == 5:
            return "\\n\\\"The Plateaux of Mirror\\\""
        elif minor == 6:
            return "\\n\\\"Possible Musics\\\"" # 1980 Collaborative
        elif minor == 7:
            return "\\n\\\"My Life in the Bush of Ghosts\\\"" # 1981
        elif minor == 8:
            return "\\n\\\"Music for Airplay\\\"" # 1981 Compilation
        elif minor == 9:
            return "\\n\\\"On Land\\\"" # 1982
        elif minor == 10:
            return "\\n\\\"Atmospheres and Soundtracks\\\"" # 1983
        elif minor == 11:
            return "\\n\\\"More Music for Films\\\"" # 1983
        elif minor == 12:
            return "\\n\\\"Working Backwards\\\"" # 1984 Compilation
    elif major == 6:
        if minor == 0:
            return "\\n\\\"The Pearl\\\"" # 1984 Collaborative
        elif minor == 1:
            return "\\n\\\"Begegnungen\\\"" # 1984 Compilation
        elif minor == 2:
            return "\\n\\\"Thursday Afternoon\\\"" # 1985
        elif minor == 3:
            return "\\n\\\"Hybrid\\\"" # 1985 Collaborative
        elif minor == 4 or minor == 5: # (there was on 6.4 release)
            return "\\n\\\"Old Land\\\"" # 1985 Compilation
        elif minor == 6 or minor == 7: # still on the desert island
            return "\\n\\\"Desert Island Selection\\\"" # 1986 Compilation
        else:
            return "\\n\\\"After Bach\\\"" # the odd one out
    elif major == 7:
        if minor == 0:
            return "\\n\\\"More Blank Than Frank\\\"" # 1986 Compilation
        if minor == 1:
            return "\\n\\\"Music for Films III\\\"" # 1988 Collaborative
        if minor == 2:
            return "\\n\\\"Wrong Way Up\\\"" # 1990 Collaborative
        if minor == 3:
            return "\\n\\\"Nerve Net\\\"" # 1992
        if minor == 4:
            return "\\n\\\"The Shutov Assembly\\\"" # 1992
        if minor == 5:
            return "\\n\\\"Neroli\\\"" # 1993
    elif major == 8:
        if minor == 0:
            return "\\n\\\"Spinner\\\"" # 1995
        if minor == 1:
            return "\\n\\\"The Drop\\\"" # 1997
        if minor == 2:
            return "\\n\\\"Tracks and Traces\\\"" # 1997
        if minor == 3:
            return "\\n\\\"Music for White Cube\\\"" # 1997
        if minor == 4:
            return "\\n\\\"Music for the Marble Palace\\\"" # 1998
        if minor == 5:
            return "\\n\\\"I Dormienti\\\"" # 1999
        if minor == 6:
            return "\\n\\\"Kite Stories\\\"" # 1999
        if minor >= 7:
            return "\\n\\\"Sonora Portraits\\\"" # 1999 Compilation
    elif major == 9:
        if minor == 0:
            return "\\n\\\"Music for Civic Recovery Centre\\\"" # 2000
        if minor == 1:
            return "\\n\\\"Music for Onmyo-Ji\\\"" # 2000 Collaborative
        if minor == 2:
            return "\\n\\\"Compact Forest Proposal\\\"" # 2001
        if minor >= 3 and minor <= 5:
            return "\\n\\\"Drawn from Life\\\"" # 2001 Collaborative
        if minor == 6:
            return "\\n\\\"Bell Studies for the Clock of the Long Now\\\"" # 2003
        if minor == 7:
            return "\\n\\\"The Equatorial Stars\\\"" # 2004 Collaborative
        if minor == 8:
            return "\\n\\\"Another Day on Earth\\\"" # 2005
        if minor == 9:
            return "\\n\\\"77 Million Paintings\\\"" # 2006
        if minor == 10:
            return "\\n\\\"Beyond Even\\\"" # 2007 Collaborative
        if minor == 11:
            return "\\n\\\"Making Space \\\"" # 2010
    return "\\\"\\\""

def options(opt):
    pass

def configure(conf):
    conf.load('misc')  # make 'command-output' available

    # TODO: Insert a sanity check for on OS X to ensure CoreAudio is present

    autowaf.check_pkg(conf, 'fftw3f', uselib_store='FFTW3F',
                      mandatory=True)
    autowaf.check_pkg(conf, 'flac', uselib_store='FLAC',
                      atleast_version='1.2.1')
    autowaf.check_pkg(conf, 'gthread-2.0', uselib_store='GTHREAD',
                      atleast_version='2.10.1')
    autowaf.check_pkg(conf, 'ogg', uselib_store='OGG', atleast_version='1.1.2')
    autowaf.check_pkg(conf, 'x11', uselib_store='X11', atleast_version='1.1', mandatory=False)
    autowaf.check_pkg(conf, 'pangoft2', uselib_store='PANGOFT2', atleast_version='1.36.8', mandatory=False)
    autowaf.check_pkg(conf, 'fontconfig', uselib_store='FONTCONFIG')

    conf.check(header_name='unistd.h', define_name='HAVE_UNISTD_H',mandatory=False)

    if conf.env.CC_NAME == 'gcc' and Options.options.strict:
        conf.define('GLIB_DISABLE_DEPRECATION_WARNINGS', 1)
        for var in ['CFLAGS', 'CXXFLAGS']:
            for lib in ['GTK', 'GTKMM']:
                for d in conf.env['INCLUDES_' + lib]:
                    conf.env.append_value(var, ['-isystem', d])

    if sys.platform == 'darwin':
        if conf.env['build_target'] in ['bigsur', 'monterey']:
            # we cannot execute test code when x-compiling ARM on Intel,
            # besides, NSWindowWillStartLiveResizeNotification is definitely available
            conf.define('HAVE_COCOA_LIVE_RESIZING', 1)
        else:
            conf.check(
                    msg              ='Checking for Cocoa live resizing constants',
                    fragment         = '#include <AppKit/NSWindow.h>\n int main(void) { (void) NSWindowWillStartLiveResizeNotification; return 0; }\n',
                    define_name      = 'HAVE_COCOA_LIVE_RESIZING',
                    uselib_store     = 'COCOA_LIVE_RESIZING',
                    compiler         = 'cc',
                    compile_filename = 'test.m',
                    execute          = True,
                    mandatory        = False)

    conf.write_config_header('gtk2ardour-config.h', remove=False)

    bak = conf.env['define_key']
    conf.define('VERSIONSTRING', conf.env['VERSION'])
    conf.define('CODENAME', enoify(int(conf.env['MAJOR']), int(conf.env['MINOR'])))
    conf.env['define_key'] = ['VERSIONSTRING', 'CODENAME' ]
    conf.write_config_header('gtk2ardour-version.h')
    conf.env['define_key'] = bak

def build(bld):
    I18N_PACKAGE = 'gtk2_ardour' + bld.env['MAJOR']

    # Tool to dump lua-bindings (of gtk2ardour + libs)
    if re.search ("linux", sys.platform) != None and bld.env['LUABINDINGDOC']:
        obj = bld (features = 'cxx c cxxprogram')
        obj.install_path = None
        obj.source    = list(gtk2_ardour_sources)
        obj.target    = 'luadoc'
        obj.includes  = ['.', '../libs', '../libs/vst3']
        obj.use       = [
                'libpbd',
                'libardour',
                'libardour_cp',
                'libtemporal',
                'libmidipp',
                'libgtkmm2ext',
                'libcanvas',
                'libwaveview',
                'libwidgets',
                'libptformat',
                ]
        obj.defines = [
                'NOMAIN',
                'PACKAGE="' + I18N_PACKAGE + '"',
                'DATA_DIR="' + autowaf.normpath(bld.env['DATADIR']) + '"',
                'CONFIG_DIR="' + autowaf.normpath(bld.env['SYSCONFDIR']) + '"',
                'LOCALEDIR="' + autowaf.normpath(bld.env['LOCALEDIR']) + '"',
                ]
        obj.linkflags = ''
        obj.uselib       = 'UUID FLAC FONTCONFIG GTHREAD GTK OGG PANGOMM CURL DL CANVAS FFTW3F LO TAGLIB XML LILV RUBBERBAND AUBIO LRDF ARCHIVE VAMPSDK VAMPHOSTSDK'
        obj.source += [ 'lua-scripting/luadoc.cc', 'platform-support/bundle_env_linux.cc' ]
        obj.use    += [ 'X11' ]
        obj.use    += [ 'libytk', 'libytkmm' ]
        obj.uselib += ' GLIBMM GIOMM PANGOMM PANGOFT2 LIBPNG LIBJPEG'

        if False and bld.is_defined('USE_EXTERNAL_LIBS'):
            obj.uselib += ' LIBAAF'
        else:
            obj.use.extend (['libaaf'])

        if bld.is_defined('HAVE_USB'):
            obj.uselib += ' USB'
        if bld.is_defined('HAVE_SUIL'):
            obj.source += [ 'plugins/lv2_plugin_ui.cc' ]
            obj.use += [ 'libsuil' ]
        if bld.is_defined('LXVST_SUPPORT'):
            obj.source += [ 'plugins/vst_plugin_ui.cc' ]
            obj.source += [ 'plugins/linux_vst_gui_support.cc', 'plugins/lxvst_plugin_ui.cc' ]
            obj.defines += [ 'LXVST_SUPPORT' ]

        if bld.is_defined('VST3_SUPPORT'):
            obj.source += [ 'plugins/vst3_plugin_ui.cc' ]
            if sys.platform == 'darwin':
                obj.source += [ 'plugins/vst3_nsview_plugin_ui.mm' ]
            elif bld.env['build_target'] == 'mingw' or bld.env['build_target'] == 'msvc':
                obj.source += [ 'plugins/vst3_hwnd_plugin_ui.cc' ]
            else:
                obj.source += [ 'plugins/vst3_x11_plugin_ui.cc' ]

#    # Tool to test libcanvas
#    if re.search ("linux", sys.platform) != None and bld.env['CANVASTESTUI']:
#        obj = bld (features = 'cxx c cxxprogram')
#        obj.install_path = None
#        obj.source    = list(gtk2_ardour_sources)
#        obj.source    = [ 'ardour_button.cc', 'session-config-dialogs/ui_config.cc', 'tooltips.cc' ]
#        obj.target    = 'canvas_test'
#        obj.includes  = ['.', '../libs']
#        obj.use       = [
#                'libpbd',
#                'libardour',
#                'libardour_cp',
#                'libtemporal',
#                'libmidipp',
#                'libgtkmm2ext',
#                'libcanvas',
#                'libptformat',
#                ]
#        obj.defines = [
#                'NOMAIN',
#                'PACKAGE="' + I18N_PACKAGE + '"',
#                'DATA_DIR="' + os.path.normpath(bld.env['DATADIR']) + '"',
#                'CONFIG_DIR="' + os.path.normpath(bld.env['SYSCONFDIR']) + '"',
#                'LOCALEDIR="' + os.path.normpath(bld.env['LOCALEDIR']) + '"',
#                ]
#        obj.linkflags = ''
#        obj.uselib    = 'UUID FLAC FONTCONFIG GLIBMM GTHREAD GTK OGG CURL DL GTKMM CANVAS FFTW3F LO TAGLIB XML '
#        # obj.source += [ 'shared-ui/canvas_test.cc', ]
#        obj.source += [ 'shared-ui/toolbar_test.cc', 'app-core/enums.cc']

    # executable version of the GTK GUI
    if bld.env['build_target'] == 'mingw' or bld.env['build_target'] == 'msvc':
        obj = bld (features = 'cxx c cxxprogram winres')
    else:
        obj = bld (features = 'cxx c cxxprogram')

    # operate on copy to avoid adding sources twice
    obj.source    = list(gtk2_ardour_sources)
    obj.target    = 'ardour-' + bld.env['VERSION']
    obj.includes  = ['.']

    if bld.is_defined('WINDOWS_VST_SUPPORT'):
        obj.includes += [ '../libs/fst' ]

    # at this point, "obj" refers to either the normal native executable
    # OR the shared library built for use with wine on linux.

    obj.use      = [ 'libpbd',
                     'libardour',
                     'libardour_cp',
                     'libtemporal',
                     'libmidipp',
                     'libgtkmm2ext',
                     'libcanvas',
                     'libwaveview',
                     'libwidgets',
                     'libptformat',
                     'libytk',
                     'libytkmm',
                     ]

    obj.defines = [
        'PACKAGE="' + I18N_PACKAGE + '"',
        'DATA_DIR="' + autowaf.normpath(bld.env['DATADIR']) + '"',
        'CONFIG_DIR="' + autowaf.normpath(bld.env['SYSCONFDIR']) + '"',
        'LOCALEDIR="' + autowaf.normpath(bld.env['LOCALEDIR']) + '"',
        ]
    obj.install_path = bld.env['DLLDIR']
    obj.linkflags    = [ bld.env['compiler_flags_dict']['execstack'] ]
    obj.uselib       = 'UUID FLAC FONTCONFIG GTHREAD OGG PANGOMM CURL DL CANVAS FFTW3F LO TAGLIB XML LILV RUBBERBAND AUBIO LRDF ARCHIVE VAMPSDK VAMPHOSTSDK GLIBMM GIOMM PANGOFT2 LIBPNG LIBJPEG'

    if bld.env['build_target'] == 'msvc':
        obj.env['LIB_LO'] = ['liblo']
        obj.use += ['liblua']
        obj.uselib += ' PANGOCAIRO GDI32'
        obj.lib = ['getopt', 'gdi32']
        obj.defines += ['NOMINMAX']

    if False and bld.is_defined('USE_EXTERNAL_LIBS'):
        obj.uselib += ' LIBAAF'
    else:
        obj.use.extend (['libaaf'])

    if bld.is_defined('HAVE_USB'):
        obj.uselib += ' USB'
    if sys.platform == 'darwin':
        obj.uselib += ' AUDIOUNITS OSX '
        obj.use    += ' libappleutility'
        obj.source += [ 'platform-support/cocoacarbon.mm', 'platform-support/bundle_env_cocoa.cc' ]
    elif bld.env['build_target'] == 'mingw':
        obj.source += [ 'platform-support/bundle_env_mingw.cc' ]
        obj.source += [ 'windows_icon.rc' ]
    elif bld.env['build_target'] == 'msvc':
        obj.source += [ 'platform-support/bundle_env_msvc2.cc' ]
        obj.source += [ 'windows_icon.rc' ]
    else:
        obj.source += [ 'platform-support/bundle_env_linux.cc' ]
        obj.use += [ 'X11' ]

    obj.includes += ['../libs']
    obj.includes += ['../libs/vst3']

    if bld.env['build_target'] == 'mingw' or bld.env['build_target'] == 'msvc':
        obj.use += [ 'PANGOFT2' ]
        obj.linkflags += bld.env['compiler_flags_dict']['mwindows']

    if bld.is_defined('HAVE_SUIL'):
        obj.source += [ 'plugins/lv2_plugin_ui.cc' ]
        obj.use += [ 'SUIL' ]

    if bld.is_defined('HAVE_FFTW35F') and bld.env['build_target'] != 'mingw' and bld.env['build_target'] != 'msvc':
        bld.env['LIB_FFTW3F'] += ['fftw3f_threads']

    if bld.is_defined('NEED_INTL'):
        obj.linkflags.append ('-lintl')

    if bld.is_defined('WINDOWS_VST_SUPPORT'):
        obj.source += [ 'plugins/windows_vst_plugin_ui.cc' ]
        obj.defines += [ 'WINDOWS_VST_SUPPORT' ]

    if bld.is_defined('LXVST_SUPPORT'):
        obj.source += [ 'plugins/linux_vst_gui_support.cc', 'plugins/lxvst_plugin_ui.cc' ]
        obj.defines += [ 'LXVST_SUPPORT' ]

    if bld.is_defined('MACVST_SUPPORT'):
        obj.source += [ 'plugins/mac_vst_plugin_ui.mm' ]
        obj.defines += [ 'MACVST_SUPPORT' ]

    if bld.is_defined('WINDOWS_VST_SUPPORT') or bld.is_defined('LXVST_SUPPORT') or bld.is_defined ('MACVST_SUPPORT'):
        obj.source += [ 'plugins/vst_plugin_ui.cc' ]

    if bld.is_defined('PHONE_HOME'):
        obj.defines += [ 'PHONE_HOME' ]

    if bld.is_defined('HAVE_COREAUDIO'):
        TaskGen.task_gen.mappings['.mm'] = TaskGen.task_gen.mappings['.cc']
        obj.use += ' libappleutility '

    if bld.is_defined('AUDIOUNIT_SUPPORT'):
        obj.source += [ 'plugins/au_pluginui.mm' ]

    if bld.is_defined('VST3_SUPPORT'):
        obj.source += [ 'plugins/vst3_plugin_ui.cc' ]
        if sys.platform == 'darwin':
            obj.source += [ 'plugins/vst3_nsview_plugin_ui.mm' ]
        elif bld.env['build_target'] == 'mingw' or bld.env['build_target'] == 'msvc':
            obj.source += [ 'plugins/vst3_hwnd_plugin_ui.cc' ]
        else:
            obj.source += [ 'plugins/vst3_x11_plugin_ui.cc' ]

    # Wrappers

    wrapper_subst_dict = {
            'INSTALL_PREFIX' : bld.env['PREFIX'],
            'LIBDIR'         : os.path.normpath(bld.env['DLLDIR']),
            'DATADIR'        : os.path.normpath(bld.env['DATADIR']),
            'CONFDIR'        : os.path.normpath(bld.env['CONFDIR']),
            'LIBS'           : 'build/libs',
            'VERSION'        : bld.env['VERSION'],
            'EXECUTABLE'     : 'build/gtk2_ardour/ardour-' + bld.env['VERSION']
    }

    if bld.env['build_target'] in ('mingw', 'msvc') and sys.platform == "win32":
        wrapper_subst_dict.update({
            'LD_LIBRARY_PATH': 'PATH'
        })
    else:
        wrapper_subst_dict.update({
            'LD_LIBRARY_PATH': 'LD_LIBRARY_PATH'
        })

    def set_subst_dict(obj, dict):
        for i in dict:
            setattr(obj, i, dict[i])

    obj              = bld(features = 'subst')
    obj.source       = 'ardev_common.sh.in'
    obj.target       = 'ardev_common_waf.sh'
    obj.chmod        = Utils.O755
    obj.dict         = wrapper_subst_dict
    set_subst_dict(obj, wrapper_subst_dict)

    obj              = bld(features = 'subst')
    obj.source       = 'ardour.sh.in'
    obj.target       = 'ardour' + bld.env['MAJOR']
    obj.chmod        = Utils.O755
    obj.dict         = wrapper_subst_dict
    obj.install_path = bld.env['BINDIR']
    set_subst_dict(obj, wrapper_subst_dict)

    # Font configuration

    font_subst_dict = {}
    font_sizes      = {}

    # Set up font sizes
    if sys.platform == 'darwin':
        basefont = ""
        font_sizes = {
                'VERYSMALL' : '7',
                'SMALLER' : '9',
                'SMALL' : '10',
                'NORMAL' : '11',
                'BIG' : '13',
                'BIGGER' : '17',
                'LARGE' : '18',
                'LARGER' : '28',
                'HUGER' : '36',
                'MASSIVE' : '60',
        }
        font_names = {
                'MONOSPACE' : 'ArdourMono',
                'CLOCKFONT' : 'ArdourMono',
                }
    else: # Linux/X11 & Windows fonts
        basefont = '' # unspecified - use system defaults
        font_sizes = {
                'VERYSMALL' : '8',
                'SMALLER' : '6',
                'SMALL' : '7',
                'NORMAL' : '8',
                'BIG' : '11',
                'BIGGER' : '13.5',
                'LARGE' : '14.5',
                'LARGER' : '19',
                'HUGER' : '27',
                'MASSIVE' : '48',
        }
        font_names = {
                'MONOSPACE' : 'ArdourMono',
                'CLOCKFONT' : 'ArdourMono',
        }

    # Set up font substitution dictionary
    # @FONT_XXXX@
    for style in ['', 'BOLD', 'ITALIC']:
        for sizename,points in iter(font_sizes.items()):
            if (len (style)):
                key = "_".join (['FONT',style,sizename])
                fontstyle = " ".join ([basefont,style.lower(),points])
            else:
                key = "_".join (['FONT',sizename])
                fontstyle = " ".join ([basefont,points])

            font_subst_dict[key] = fontstyle

    # @FONT_SIZE_XXXX@
    for sizename,points in iter(font_sizes.items()):
        key = "_".join (['FONT_SIZE',sizename])
        font_subst_dict[key] = points

    # various font names, eg @BOLD_MONOSPACE@
    for font_sym,text in iter(font_names.items()):
        key = font_sym
        font_subst_dict[key] = text

    font_subst_dict['FONTFAMILY'] = ''
    # RC file

    obj              = bld(features = 'subst')
    obj.source       = [ 'clearlooks.rc.in' ]
    obj.target       = 'clearlooks.rc'
    obj.install_path = bld.env['CONFDIR']
    set_subst_dict(obj, font_subst_dict)

    font_subst_dict['FONTFAMILY'] = 'ArdourSans'

    obj              = bld(features = 'subst')
    obj.source       = [ 'clearlooks.rc.in' ]
    obj.target       = 'clearlooks.ardoursans.rc'
    obj.install_path = bld.env['CONFDIR']
    set_subst_dict(obj, font_subst_dict)

    obj              = bld(features = 'subst')
    obj.source       = [ 'default_ui_config.in' ]
    obj.target       = 'default_ui_config'
    obj.install_path = bld.env['CONFDIR']
    set_subst_dict(obj, font_subst_dict)

    # Menus
    menus_argv = []
    if sys.platform == 'darwin':
        menus_argv = [ '-E', '-P', '-D__APPLE__', '-' ]
    elif bld.env['build_target'] == 'msvc':
        menus_argv = [ '/EP', '/nologo' ]
    else:
        menus_argv = [ '-E', '-P' ]

    if bld.is_defined('MIXBUS'):
        menus_argv += [ '-DMIXBUS' ]

    if bld.is_defined('PTFORMAT'):
        menus_argv += [ '-DPTFORMAT' ]

    if bld.is_defined('MIXBUS') or bld.env['DEBUG']:
        menus_argv += [ '-DVAPOR' ]

    if not bld.env['DEBUG']:
        menus_argv += [ '-DNDEBUG' ]

    # always build all versions of the menu definitions
    # so that we can try them out with different program builds.

    obj = bld(features = 'command-output')
    if bld.env['build_target'] == 'msvc':
        obj.command = bld.env['CXX'][0]
    else:
        obj.command = 'cpp'
    obj.command_is_external = True
    obj.no_inputs = True
    obj.argv = menus_argv
    if bld.env['build_target'] == 'msvc':
        menu_path = bld.path.find_resource('ardour.menus.in').abspath()
        obj.argv += [ menu_path ]
    obj.dep_vars = ['PTFORMAT', 'MIXBUS', 'WINDOWS', 'DEBUG']
    if bld.is_defined('LIVETRAX'):
        obj.stdin = 'livetrax.menus.in'
    else:
        obj.stdin = 'ardour.menus.in'
    obj.stdout = 'ardour.menus'
    bld.install_files (bld.env['CONFDIR'], 'ardour.menus')

    # Freedesktop
    freedesktop_subst_dict = {
                    'ARDOUR_EXEC' : bld.env['lwrcase_dirname'],
                    'ARDOUR_ICON' : bld.env['lwrcase_dirname'],
                    'VERSION': bld.env['VERSION'],
                    'DATE': bld.env['DATE'],
    }

    if bld.env['FREEDESKTOP']:
        obj              = bld(features = 'subst')
        obj.source       = 'ardour.desktop.in'
        obj.target       = bld.env['lwrcase_dirname'] + '.desktop'
        obj.chmod        = Utils.O644
        obj.dict         = freedesktop_subst_dict
        set_subst_dict(obj, freedesktop_subst_dict)
        bld.install_files (os.path.join (bld.env['PREFIX'], 'share/applications'), obj.target)

        obj              = bld(features = 'subst')
        obj.source       = 'ardour-mime-info.xml'
        obj.target       = 'ardour.xml'
        obj.chmod        = Utils.O644
        bld.install_files (os.path.join (bld.env['PREFIX'], 'share/mime/packages'), obj.target)

        # build appdata with translations
        appdata_i18n_mo(bld)
        appdata_i18n_xmlin(bld)
        obj              = bld(features = 'subst')
        obj.source       = 'ardour.appdata.xml.in'
        obj.target       = bld.env['lwrcase_dirname'] + '.appdata.xml'
        obj.chmod        = Utils.O644
        obj.dict         = freedesktop_subst_dict
        set_subst_dict(obj, freedesktop_subst_dict)
        bld.install_files (os.path.join (bld.env['PREFIX'], 'share/appdata'), obj.target)

        # install desktop icon files
        icon_file_name = bld.env['lwrcase_dirname'] + '.png'
        bld.install_as('${PREFIX}/share/icons/hicolor/16x16/apps/' + icon_file_name, 'resources/Ardour-icon_16px.png')
        bld.install_as('${PREFIX}/share/icons/hicolor/22x22/apps/'+ icon_file_name, 'resources/Ardour-icon_22px.png')
        bld.install_as('${PREFIX}/share/icons/hicolor/32x32/apps/'+ icon_file_name, 'resources/Ardour-icon_32px.png')
        bld.install_as('${PREFIX}/share/icons/hicolor/48x48/apps/'+ icon_file_name, 'resources/Ardour-icon_48px.png')
        bld.install_as('${PREFIX}/share/icons/hicolor/256x256/apps/'+ icon_file_name, 'resources/Ardour-icon_256px.png')
        bld.install_as('${PREFIX}/share/icons/hicolor/512x512/apps/'+ icon_file_name, 'resources/Ardour-icon_512px.png')

    # Keybindings

    # NATIVE ARDOUR BINDING FILES
    # explicitly state the use of perl here so that it works on windows too
    #
    #
    # ***** NOTE: THE CANONICAL LIST OF FILES PROCESSED FOR BINDINGS IS INSIDE ../tools/fmt-bindings
    #
    # If you add or delete some ,bindings files, be sure to edit fmt_bindings too, or better yet,
    # hack fmt-bindings and this wscript file so that the list is defined here and passed in.
    perl = os.environ.get('ARDOUR_PERL') or 'C:/Program Files/Git/usr/bin/perl.exe'
    a_rule = '"%s" %s/tools/fmt-bindings --platform="%s" --winkey="%s" --accelmap 1 ${SRC[0].abspath()} >${TGT}' % (perl, bld.top_dir, sys.platform, bld.env['WINDOWS_KEY'] )
    for b in [ 'ardour' ] :
        obj = bld(
            target = b + '.keys',
            source = [ b + '.keys.in', 'mixer.bindings', 'processor_box.bindings', 'step_editing.bindings', 'monitor.bindings', 'trigger.bindings', 'regionfx_box.bindings', 'automation.bindings' ],
            rule = a_rule
            )
        obj.install_path = bld.env['CONFDIR']

    # Icons/Images
    bld.install_files(os.path.join (bld.env['DATADIR'], 'icons'), bld.path.ant_glob('icons/*.png'))
    bld.install_files(bld.env['DATADIR'], 'ArdourMono.ttf')
    bld.install_files(bld.env['DATADIR'], 'ArdourSans.ttf')

    # Application/Product specific resources (icon, splash)
    pgmname = bld.env['PROGRAM_NAME']
    bld.install_files(os.path.join(bld.env['DATADIR'], 'resources'), bld.path.ant_glob('resources/' + pgmname + '*'))

    if bld.env['build_target'] == 'mingw' or bld.env['build_target'] == 'msvc':
        # These icons need to overwrite the files already installed in the icons
        # directory above. Do this in the external packaging scripts for now.
        #bld.install_files(os.path.join (bld.env['DATADIR'], 'icons'), bld.path.ant_glob('icons/cursor_square/*.png'))
        bld.install_files(os.path.join (bld.env['DATADIR'], 'icons'), 'icons/cursor_square/hotspots')

    # Default UI configuration
    bld.install_files(bld.env['CONFDIR'], 'default_ui_config')
    # Color Themes. Find each color file for this program only
    # and install
    bld.install_files (os.path.join(bld.env['DATADIR'], 'themes'), bld.path.ant_glob ('themes/*-' + pgmname.lower() + '.colors'))

    # Default export stuff
    bld.install_files(os.path.join(bld.env['CONFDIR'], 'export'), bld.path.ant_glob('export/*.format'))

    # i18n
    if bld.is_defined('ENABLE_NLS'):
        mo_files = bld.path.ant_glob('po/*.mo')
        for mo in mo_files:
            lang = os.path.basename(mo.srcpath()).replace('.mo', '')
            bld.install_as (os.path.join(os.path.normpath(bld.env['LOCALEDIR']), lang, 'LC_MESSAGES', I18N_PACKAGE + '.mo'),
                            mo)

def i18n_func(bld):
    I18N_PACKAGE = 'gtk2_ardour' + bld.env['MAJOR']
    autowaf.build_i18n(bld, '.', 'gtk2_ardour', I18N_PACKAGE, gtk2_ardour_sources,
                       'Paul Davis')
    appdata_i18n_pot(bld)
    appdata_i18n_po(bld)
    appdata_i18n_mo(bld)

def i18n_pot_func(bld):
    I18N_PACKAGE = 'gtk2_ardour' + bld.env['MAJOR']
    autowaf.build_i18n_pot(bld, '.', 'gtk2_ardour', I18N_PACKAGE, gtk2_ardour_sources,
                           'Paul Davis')
    appdata_i18n_pot(bld)

def i18n_po_func(bld):
    I18N_PACKAGE = 'gtk2_ardour' + bld.env['MAJOR']
    autowaf.build_i18n_po(bld, '.', 'gtk2_ardour', I18N_PACKAGE, gtk2_ardour_sources,
                          'Paul Davis')
    appdata_i18n_po(bld)

def i18n_mo_func(bld):
    I18N_PACKAGE = 'gtk2_ardour' + bld.env['MAJOR']
    autowaf.build_i18n_mo(bld, '.', 'gtk2_ardour', I18N_PACKAGE, gtk2_ardour_sources,
                          'Paul Davis')

def appdata_i18n_pot(bld):
    potfile = os.path.join(bld.top_dir, 'gtk2_ardour', 'appdata',
            'ardour.appdata.pot')
    if bld.cmd in ('i18n_pot', 'i18n'):
        Logs.info('Generating pot file from Ardour appdata')
        itsfile = os.path.join(bld.top_dir, 'tools', 'as-metainfo.its')
        adsource = os.path.join(bld.top_dir, 'gtk2_ardour',
                'ardour.appdata.xml.in.in')
        Logs.info('Updating ' + potfile)
        try:
            subprocess.call(('itstool', '-i', itsfile, '-o', potfile, adsource))
        except:
            print ('Error processing appdata pot file - ignored')
    elif bld.cmd == 'clean' and os.path.exists(potfile):
        Logs.info('Removing Ardour appdata pot file')
        os.remove(potfile)

def appdata_i18n_po(bld):
    autowaf.build_i18n_po(bld, bld.top_dir, os.path.join(
        'gtk2_ardour', 'appdata'), 'ardour.appdata', 'dummy', 'dummy')

def appdata_i18n_mo(bld):
    autowaf.build_i18n_mo(bld, bld.top_dir, os.path.join(
        'gtk2_ardour', 'appdata'), 'ardour.appdata', 'dummy', 'dummy')

def appdata_i18n_xmlin(bld):
    adxmlinfile = os.path.join(bld.top_dir, 'gtk2_ardour',
            'ardour.appdata.xml.in')
    if bld.cmd == 'build':
        itsfile = os.path.join(bld.top_dir, 'tools', 'as-metainfo.its')
        adxmlininfile = os.path.join(bld.top_dir, 'gtk2_ardour',
                'ardour.appdata.xml.in.in')
        mo_glob = os.path.join(bld.top_dir, 'gtk2_ardour', 'appdata', 'po', '*.mo')
        mo_files = glob.glob(mo_glob)
        Logs.info('Generating ' + adxmlinfile)
        subprocess.call(['itstool', '-i', itsfile, '-o', adxmlinfile,
            '-j', adxmlininfile] + mo_files)
    elif bld.cmd == 'clean' and os.path.exists(adxmlinfile):
        Logs.info('Removing ' + adxmlinfile)
        os.remove(adxmlinfile)
